#!/usr/bin/env bash
# =================================================================================
#                                   CONFIG                                        #
#                Please read this config file carefully                           #
# =================================================================================


###################################################################################
#                                Required modules
###################################################################################

CONDA_ENV_SGA="Path_conda_env_SGA"             
FASTP_MODULE="Path_module_fastp"
PRINSEQ_LITE="Path_prinseq_lite.pl"
KRAKEN2_MODULE="Path_module_Kraken2"
BOWTIE2_MODULE="Path_module_bowtie2"
SAMTOOLS_MODULE="Path_module_samtools"
MMSEQS2_MODULE="Path_module_MMseqs2"
MMSEQS2_DATA_MODULE="Path_module_MMseqs2_data"
CONDA_ENV_FILTERBAM="Path_conda_env_bam-filter"
CONDA_ENV_ngsLCA="Path_conda_env_ngsLCA"
PDC_MODULE="PDC"                 
KRONATOOLS_MODULE="Path_module_kronatools"
CONDA_ENV_PLOTS="Path_conda_env_plots"

# ---- bamdam from Python venv ----
# Optional: module to load before activating the venv (kept generic).
# If bamdam is already in PATH (installed via pip), leave these empty
BAMDAM_PYTHON_MODULE="Path_module_python"
BAMDAM_VENV="Path_python_env_bamdam-env"
TAXADB_VENV="Path_python_env_taxadb" #plus install pandas through pip

###################################################################################
#                        Input files
###################################################################################

# 1) If you want to run the whole pipeline from raw sequencing data
# Point the path of your raw sequencing files or to a list containing the path of each samples to be processed
#If a list is provided, it will perform the samples contained in it preferentially and READS_GLOB won't be perform
READS_GLOB="Path_samples/*.fastq.gz" #e.g. READS_GLOB="/data/project/*_1.fastq.gz" or READS_GLOB="/data/project/*_R1.fastq.gz"
READS_LIST="Path_samples/List_fastq.txt"   # e.g. "/data/project/my_fastqs.list"

KRAKEN_REQUIRE_PRIMARY=1  #If you want to run Kraken GTDB on every sga or prinseq files present in the respective folder, set it to 0
MAP_REQUIRE_PRIMARY=1 #If you want to run mapping on every kraken files present in the kraken folder, set it to 0

# 2) If you want to run from any other steps, with files not generated by the pipeline, provide a list of files from the step before with absolute path 
# Note: In this case, only the samples provided in the external files list will be performed, not the one provided from sequencing data to the pipeline

# Format: either one absolute path per line, or "SAMPLE<TAB>/abs/path/to/SAMPLE_merged.fastq.gz"
OVERRIDE_LIST_FASTP="" # Give absolute path - In the case you are not using fastp to preprocess the reads
OVERRIDE_LIST_SGA="" #"/cfs/klemming/projects/supr/sllstore2017093/sediment/nathan/pipeline_metage_out/01_fastp/List_SGA.txt" # Give absolute path
OVERRIDE_LIST_PRINSEQ="" #"/cfs/klemming/projects/supr/sllstore2017093/sediment/nathan/pipeline_metage_out/01_fastp/List_Prinseq.txt"
OVERRIDE_LIST_KRAKEN="" #"/cfs/klemming/projects/supr/sllstore2017093/sediment/nathan/List_Kraken.txt" # Give absolute path
OVERRIDE_LIST_MAPPING="" #"/cfs/klemming/projects/supr/sllstore2017093/sediment/nathan/List_mapping.txt"" # Give absolute path
OVERRIDE_LIST_FILTER="" #"/cfs/klemming/projects/supr/sllstore2017093/sediment/nathan/pipeline_metage_out/04_mapping/List_filter.txt" # Give absolute path
OVERRIDE_LIST_MMSEQS2="/cfs/klemming/projects/supr/sllstore2017093/sediment/nathan/mmseqs2_test.list"
OVERRIDE_LIST_METRICS="" #"/absolute/path/to/List_filter.txt"

# If you already have SGA output (name: <sample>_merged.dust.rmdup.fastq.gz)
SGA_OUT_DIR=""
# If you already have Kraken2 unclassified (name: <sample>_GTDB_unclas.fastq.gz)
KRAKEN_UNCLAS_DIR=""
# If you already have mapping BAMs (name: <sample>.b2.k1000.all.sorted.bam)
MAPPING_BAM_DIR=""


###################################################################################
#                        Path to scripts and databases
###################################################################################

SCRIPTS_DIR="Path_scripts_directory"

# NOTE: Please verify your DB versions are current; if DBs are updated, paths likely change.
#  - PhyloNorway masked bowtie2 index (prefix ending with "_"):
PHYLONORWAY="Path_DB_PhyloNorway_index"
PHYLONORWAY_HEADER="Path_DB_PhyloNorway_sq_header.tsv"
PLASTID="Path_DB_plastids_index"
MITO="Path_DB_mitochondrion_index"
MAM_BIRD_FISH="Path_DB_mam-bird-fish_v2"

# Databases to map with Bowtie2 (order matters). Space-separated list of index prefixes.
# Example:
#   MAP_DB_LIST="${PHYLONORWAY} ${PLASTID} ${MITO} ${MAM_BIRD_FISH}"
# Note: Think to add the path to the database you want to use in the mapping before
# Instance: DB1="Path2DB1"
MAP_DB_LIST="${PHYLONORWAY} ${PLASTID} ${MITO} ${MAM_BIRD_FISH}"

# Optional: explicitly select which mapping run folder to use when filtering-only.
# This must match the folder suffix created by mapping:
# 04_mapping/<SAMPLE>/<SAMPLE>_<MAP_LAST_DB_TAG>/
# Example: nordic_fish
#MAP_LAST_DB_TAG="${MAP_LAST_DB_TAG:-}"
MAP_LAST_DB_TAG="mam-bird-fish_v2" #nordic_fish
SITE_TAG="Orsa"

# Kraken2 GTDB 
GTDB_SRC="Path_DB_GTDB"
#"/cfs/klemming/scratch/e/ernjoh/GTDB_KRAKEN2_DB" 
# NCBI taxonomy files
NAMES="Path_names_NM.dmp"
NODES="Path_nodes_NM.dmp"
ACC2TAX="Path_acc2taxid.txt.gz"

#MMSeqs2 database
MMSEQS2_DB="Path_MMSEQS2_DB_NT"
TAXADB_SQLITE="Path_taxadb_nucl.sqlite"

#### Path to roots
OUT_ROOT="Path_out"
TMP_ROOT="Path_tmp"
LOG_ROOT="Path_log"

#### Path to metadata
METADATA_PATH="Path_metadata.txt" #Carefull it needs to be as a tsv tab-delimited

# Fastp outputs by sample will go to:     ${OUT_ROOT}/01_fastp/<sample>/
# Prinseq outputs by sample will go to:   ${OUT_ROOT}/02_prinsea/<sample>/
# SGA outputs by sample will go to:       ${OUT_ROOT}/02_sga/<sample>/
# Kraken2 outputs:                        ${OUT_ROOT}/03_kraken_gtdb/
# Mapping outputs:                        ${OUT_ROOT}/04_mapping/<runname>/
# Filtering outputs:                      ${OUT_ROOT}/05_filtering/<runname>/
# Metrics & Excel:                        ${OUT_ROOT}/99_metrics/


###################################################################################
#                              Tools activation                                   #
###################################################################################

#### 1=enable, 0=disable
ENABLE_PREPROCESS=0     # If set to 0, neither fastp or SGA will run
ENABLE_FASTP=0
ENABLE_SGA=0
ENABLE_PRINSEQ=0        # set 1 to use PRINSEQ instead of SGA         
ENABLE_KRAKEN_GTDB=0
ENABLE_MAPPING=0
ENABLE_FILTERING=0      # If set to 0, neither filterBAM or ngsLCA or bamdam will run
ENABLE_FILTERBAM=0
ENABLE_NGSLCA=0
ENABLE_BAMDAM=0
ENABLE_MMSEQS2=0
ENABLE_METRICS=1
ENABLE_PLOTS=1

#### Force re-run switches (0/1). When 1, submit the step even if its outputs exist.
FORCE_FASTP=1
FORCE_SGA=1
FORCE_KRAKEN=1
FORCE_MAPPING=1
FORCE_FILTER=1
FORCE_MMSEQS2=1
 
###################################################################################
#                       Tools' parameters to precise
###################################################################################

# fastp
FASTP_OVERLAP_LEN_REQUIRE=20   # --overlap_len_require
FASTP_MIN_LENGTH=30            # -l
# SGA
SGA_DUST_THRESHOLD=4           # --dust-threshold
SGA_CLEAN_INDEX=1              # 0 (disable) or 1 (enable). If enable it will remove all index files after sga step is done, to get extra space
# PRINSEQ params (defaults mirror your snippet)
PRINSEQ_COMPLEXITY_METHOD="dust"
PRINSEQ_COMPLEXITY_THRESHOLD=4
PRINSEQ_MIN_LEN=35
PRINSEQ_DEREP="14"                      # exact fwd+rev duplicates
# Mapping run name (used to bundle outputs)
#MAP_RUN="default_run"
# bamdam parameters (used only if ENABLE_BAMDAM=1)
BAMDAM_STRANDED="ds"          # "ds" or "ss"
BAMDAM_MINREADS=5             # for bamdam krona --minreads
BAMDAM_MAXDAMAGE=0.5          # for bamdam krona --maxdamage
TOP_GENUS=10                  # Top X genus to plot for damage
BAMDAM_TAXA_PER_PLOT=50       # Number of taxa passing the filters to plot per graph

# MMseqs2 search settings (optional, but good to centralize)
MMSEQS2_THREADS=60
MMSEQS2_MAX_SEQS=300
MIN_SEQID=0.85
MIN_BITS=50
MIN_QUERY_COV=0.95
MAX_EVALUE="1e-5"
MMSEQS2_S=7.5
MMSEQS2_SPACED_KMER_MODE=1
MMSEQS2_SPLIT_MEM_LIMIT="220G"
# MMSeqs2 evaluation parameters
MMSEQS2_TOP_GENERA=10
MMSEQS2_GENERA_FILE="list_mmseqs.txt" #If a list file is give, the genera selected for investigation through MMSeqs2 will be provided from the list file and the TOP_GENERA argument will be skipped. The lsit should be in shape of 1 genera name per line.
MMSEQS2_MIN_DMG=3.5
MMSEQS2_MAX_READS=100
MMSEQS2_MIN_READS=30
MMSEQS2_SEED="42"               # Leave empty to have different reads each run, othewise set an integer (e.g. 42)
MMSEQS2_AMBIG_FRAC=0.05         # Percent of e-value difference for the second best hit for a different genera than the mmseqs2 best hit 

# Plot parameters
PLOTS_BAMDAM_MIN_READS=50       # Minimum reads per sample to include in bamdam plots
PLOTS_BAMDAM_PLOT_MODE="both"   # heatmap, bubble, both
PLOTS_DAMAGE_THRESHOLD=3.5      # Minimum percentage of damage for plotting
PLOTS_PLOT_LOW_DAMAGE_TAXA=0    # 1 = keep low-damage taxa (default); 0 = drop taxa whose max damage across samples is < PLOTS_DAMAGE_THRESHOLD
PLOTS_EXCLUDE_TAXA="Homo;Zea;Canis;Veronica" # comma / semicolon / space separated (exact taxon name matches)
PLOTS_KRONA=1                   # Plots the bamdam results for all samples in metadata if enable. 1=enable, 0=disable
PLOTS_LIST_TAXA_EVOLUTION_FILE=taxa_list_reads_single_plot.txt # Give a list of taxa with one taxa per line, to produce plot of abundance of each taxa as a line representation
########################################################################################################
#                                        SBATCH parameters
# Note: These paramaters are designed for running ~150 Millions of reads at a time on Dardel PDC cluster
########################################################################################################

##### Global SBATCH defaults
SBATCH_DEFAULT_ACCOUNT="account_project"
SBATCH_DEFAULT_PARTITION="shared"
SBATCH_DEFAULT_CPUS="32"
SBATCH_DEFAULT_MEM="28G"
SBATCH_DEFAULT_TIME="2:00:00"
SBATCH_DEFAULT_QOS=""
SBATCH_DEFAULT_EXTRA=""

##### Per-step SBATCH overrides (examples shown)
# FASTP
FASTP_SBATCH_ACCOUNT="account_project"
FASTP_SBATCH_PARTITION="shared"
FASTP_SBATCH_CPUS="32"
FASTP_SBATCH_MEM="28G"
FASTP_SBATCH_TIME="2:00:00"
FASTP_SBATCH_QOS=""
FASTP_SBATCH_EXTRA=""
FASTP_SBATCH_JOB_NAME="fastp_merge"

# SGA
SGA_SBATCH_ACCOUNT="account_project"
SGA_SBATCH_PARTITION="shared"
SGA_SBATCH_CPUS="32"
SGA_SBATCH_MEM="28G"
SGA_SBATCH_TIME="2:00:00"
SGA_SBATCH_QOS=""
SGA_SBATCH_EXTRA=""
SGA_SBATCH_JOB_NAME="SGA"

# SLURM for PRINSEQ array
PRINSEQ_SBATCH_ACCOUNT="account_project"
PRINSEQ_SBATCH_PARTITION="shared"
PRINSEQ_SBATCH_CPUS="62"
PRINSEQ_SBATCH_MEM="50G"
PRINSEQ_SBATCH_TIME="8:00:00"
PRINSEQ_SBATCH_QOS=""
PRINSEQ_SBATCH_EXTRA=""
PRINSEQ_SBATCH_JOB_NAME="prinseq"

# Kraken2
KRAKEN_SBATCH_ACCOUNT="account_project"
KRAKEN_SBATCH_PARTITION="memory"
KRAKEN_SBATCH_CPUS="256" 
KRAKEN_SBATCH_MEM="650G"         
KRAKEN_SBATCH_TIME="1-10:00:00"
KRAKEN_SBATCH_QOS=""
KRAKEN_SBATCH_EXTRA=""
KRAKEN_SBATCH_JOB_NAME="GTDB"

# Mapping
MAP_SBATCH_ACCOUNT="account_project"
MAP_SBATCH_PARTITION="memory"
MAP_SBATCH_CPUS="256"
MAP_SBATCH_MEM="550G"
MAP_SBATCH_TIME="0-10:00:00"
MAP_SBATCH_QOS=""
MAP_SBATCH_EXTRA=""
MAP_SBATCH_JOB_NAME="bowtie2"

# Filtering / ngsLCA
FILTER_SBATCH_ACCOUNT="account_project"
FILTER_SBATCH_PARTITION="memory"
FILTER_SBATCH_CPUS="32"
FILTER_SBATCH_MEM="28G"
FILTER_SBATCH_TIME="0-01:00:00"
FILTER_SBATCH_QOS=""
FILTER_SBATCH_EXTRA=""
FILTER_SBATCH_JOB_NAME="filtering_ngslca"

# MMSeqs2
MMSEQS2_SBATCH_ACCOUNT="account_project"
MMSEQS2_SBATCH_PARTITION="memory"
MMSEQS2_SBATCH_CPUS="256"
MMSEQS2_SBATCH_MEM="880G"
MMSEQS2_SBATCH_TIME="08:10:00"
MMSEQS2_SBATCH_QOS=""
MMSEQS2_SBATCH_EXTRA=""
MMSEQS2_SBATCH_JOB_NAME="mmseqs2"

# Metrics
METRICS_SBATCH_ACCOUNT="account_project"
METRICS_SBATCH_PARTITION="shared"
METRICS_SBATCH_CPUS="8"
METRICS_SBATCH_MEM="10G"
METRICS_SBATCH_TIME="02:00:00"
METRICS_SBATCH_QOS=""
METRICS_SBATCH_EXTRA=""
METRICS_SBATCH_JOB_NAME="metrics"

# Plots
PLOTS_SBATCH_ACCOUNT="account_project"
PLOTS_SBATCH_PARTITION="shared"
PLOTS_SBATCH_CPUS="8"
PLOTS_SBATCH_MEM="10G"
PLOTS_SBATCH_TIME="00:30:00"
PLOTS_SBATCH_QOS=""
PLOTS_SBATCH_EXTRA=""
PLOTS_SBATCH_JOB_NAME="plots"

#------------------------------------------------------------------------------------------------------------#
###                       IMPORTANT TO DO BEFORE TO RUN ANY MAPPING SCRIPT                                 ###
#------------------------------------------------------------------------------------------------------------#
#                 Please index all your database with bowtie2 otherwise it won't run                         #
#      Check carefully the disk space, so you don't have any jobs being killed for out of disk space         #
# Carefull about the input fastq.gz -> Better to add it as Sample_name_1.fastq.gz and Sample_name_2.fastq.gz #
# Don't forget to precise the MAP_LAST_DB_TAG, especially if you run the filtering or mapping step alone     #
#------------------------------------------------------------------------------------------------------------#
